### ISSUE TITLE
Compilation error with Xcode 11

### ISSUE THREAD

**Issue by skrew** [fxm90/LightweightObservable#3]
Hi,

Using the master branch (and GradientLoadingBar), i still have 2 errors:

```Initializer does not override a designated initializer from its superclass```
```'Observable<T>' initializer is inaccessible due to 'private' protection level```

in `Observable.swift`, line 106

Thanks

**Comment by fxm90** [comment]
Oh my gosh I'm so sorry!! This was an invalid auto-correction from Swiftformat, which I didn't had a further look into. I've redeployed the version, can you please check again? 🙂

**Comment by skrew** [comment]
Fix was fast !!!

Seems ok for me, no more build error (but i still have some errors in others libraries, so i can't test changes on a device).

BTW i can close this issue. 
Thanks again ;)
