### ISSUE TITLE
Minimum deployment target 15

### ISSUE THREAD

**Issue by alinfarcas12** [fxm90/LightweightObservable#9]
Hi!
Can you please lower the minimum deployment target? I am using GradientLoadingBar which uses latest version of LightweightObservable, and my project has it's target set to iOS 13.
p.s. i am using carthage

Thanks

**Comment by fxm90** [comment]
Hey @alinfarcas12 

Thanks for reporting. I could verify the issue and will try to provide a fix later this day.

**Comment by fxm90** [comment]
@alinfarcas12 I've released new versions of `LightweightObservable` and `GradientLoadingBar` that should fix the issue.

**Comment by alinfarcas12** [comment]
Wow. That was fast.
I can confirm that it's ok right now.
Thanks!
